config/routes.rb
Rails.application.routes.draw do
  root "questions#index"

  resources :questions do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
include Visible
  belongs_to :question

end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
    
    class_methods do
      def public_count
        where(status: 'public').count
      end
    end

    def archived?
      status == 'archived'
    end
  end

app/models/question.rb
class Question < ApplicationRecord
    include Visible
    has_many :comments, dependent: :destroy
  
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }


  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @question = Question.find(params[:question_id])
      @comment = @question.comments.create(comment_params)
      redirect_to question_path(@question)
    end
  
    def destroy
      @question = Question.find(params[:question_id])
      @comment = @question.comments.find(params[:id])
      @comment.destroy
      redirect_to question_path(@question)
    end

    private
      def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
      end
  end
  

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to root_path
  end

  private
    def question_params
      params.require(:question).permit(:title, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.question, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @question, @question.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>

    <div>
      <%= form.label :status %><br>
      <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qtracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% question.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% question.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :status %><br>
      <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/questions/edit.html.erb
<h1> Edit Article</h1>

<%= render "form", question: @question%>

app/views/questions/index.html.erb
<h1>Questions</h1>


Our tracker has <%= Question.public_count %> questions and counting!

<ul>
  <% @questions.each do |question| %>
    <% unless question.archived? %>
      <li>
        <%= link_to question.title, question %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Question", new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<% render "form", question: @question %>

<%= form_with model: @question do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @question.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% @question.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<p><%= @question.body %></p>

<ul>
  <li><%= link_to "Edit", edit_question_path(@question) %></li>
  <li><%= link_to "Destroy", question_path(@question),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

<h2>Comments</h2>
<% render @question.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>